name: mortgage
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  go_router: ^10.2.0
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  intl: ^0.18.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.7
  json_annotation: ^4.8.1
  persistent_bottom_nav_bar: ^5.0.2
  
  http: ^1.1.0
  in_app_review: ^2.0.6
  dio: ^5.3.2
  flutter_inappwebview: ^5.7.2+3
  
  firebase_core: ^2.21.0
  flutter_local_notifications: ^9.8.0+1
  overlay_support: ^2.1.0
  firebase_remote_config: ^4.3.3
  firebase_analytics: ^10.6.3
  firebase_messaging: ^14.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
